# -*- mode: python ; coding: utf-8 -*-
#
# ArduCheck.spec — Configuración de PyInstaller para ArduCheck
# Optimizado: excluye módulos innecesarios para reducir el tamaño del .exe

a = Analysis(
    ['gui\\app_v2.py'],
    pathex=['.'],
    binaries=[],
    datas=[],
    hiddenimports=[
        'serial',
        'serial.tools.list_ports',
        'serial.tools.list_ports_windows',
        'serial.tools.list_ports_osx',
        'serial.tools.list_ports_posix',
        'usb.core',
        'usb.util',
        'usb.backend.libusb1',
        'usb.backend.libusb0',
        'usb.backend.openusbd',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[
        # Módulos de test y desarrollo
        'tkinter.test',
        'unittest',
        'pydoc',
        'pydoc_data',
        'doctest',
        'test',
        # XML/HTML (no se usa en ArduCheck)
        'xml.etree',
        'xml.dom',
        'xml.dom.minidom',
        'xml.dom.pulldom',
        'xml.sax',
        'xmlrpc',
        'html',
        'html.entities',
        # Ciencia/datos (no se usa)
        'numpy',
        'numpy.core',
        'pandas',
        'matplotlib',
        'scipy',
        # GUIs alternativas (no se usa)
        'PyQt5',
        'PyQt6',
        'PySide2',
        'PySide6',
        'wx',
        'IPython',
        # Otros
        'pytest',
        'setuptools',
        'distutils',
        'ensurepip',
        'venv',
        'lib2to3',
        'tarfile',
        'zipfile',
        'gzip',
        'bz2',
        'lzma',
        'mailbox',
        'mail',
        ' mimetypes',
        'turtle',
        'turtledemo',
        'colorsys',
        'crypt',
        'sunau',
        'aifc',
        'chunk',
        'wave',
        'spwd',
        'nis',
        'optparse',
        'imp',
        'macpath',
        'macurl2path',
        'plat-linux2',
        'plat-darwin',
        'imghdr',
        'spwd',
        'sndhdr',
        'ossaudiodev',
        'audiodev',
        'sunaudiodev',
        'os2emxpath',
        'readline',
        'pty',
        'tty',
        'grp',
        'pty',
        'fcntl',
        'resource',
        'syslog',
        'pwd',
        'dbm',
        'anydbm',
        'dbhash',
        'dumbdbm',
        'whichdb',
        'msilib',
        'mmap',
        'nis',
        'nis',
    ],
    noarchive=False,
    optimize=1,  # Nivel 1 = eliminar assert y __debug__
)
pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.datas,
    [],
    name='ArduCheck',
    debug=False,
    bootloader_ignore_signals=False,
    strip=True,           # Strip símbolos de depuración
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon=None,
)
